/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bhagavathi.n' at '6/27/16 7:03 PM' with Gradle 2.12
 *
 * @author bhagavathi.n, @date 6/27/16 7:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
